[build-system]
build-backend = "hatchling.build"
requires = ["hatchling >=1.12.2"]

[project]
dependencies = []
description = "Install Conda and friends on Google Colab, easily"
license = "MIT"
name = "condacolab"
readme = "README.md"
requires-python = ">=3.10"
version = "0.2.0a"

[[project.authors]]
email = "jaimergp@users.noreply.github.com"
name = "Jaime Rodríguez-Guerra"

[project.urls]
homepage = "https://github.com/conda-incubator/condacolab"
repository = "https://github.com/conda-incubator/condacolab"

[tool.ruff]
line-length = 99
